site_name:           ProbabilisticNetowrk.jl
repo_url:            https://github.com/PoisotLab/ProbabilisticNetowrk.jl
site_description:    Analysis of probabilistic ecological networks.
site_author:         Timothée Poisot
theme:               readthedocs
markdown_extensions: [tables, fenced_code]
pages:
    - ['index.md', 'Introduction']
    - ['api.md', 'API']
