site_name: EcologicalNetwork.jl
repo_url: https://github.com/PoisotLab/EcologicalNetwork.jl
site_description: Analysis of ecological networks
site_author: Timothée Poisot

theme: material

extra:
  logo: "images/logo.png"
  palette:
    primary: 'green'
    accent: 'deep orange'
  author:
    twitter: poisotlab
    github: poisotlab

extra_css:
  - assets/Documenters.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - codehilite
  - admonition

docs_dir: 'build'

pages:
  - Home: index.md
  - "Different types of networks": types.md
  - "Datasets": data.md
  - "Use cases":
    - Nestedness: usecase/nestedness.md
    - Modularity: usecase/modularity.md
    - Motifs: usecase/motifs.md
  - "Network structure":
    - "Linkage density and connectance": community/nlinks.md
    - "Degree distribution": community/degree.md
    - "Interaction motifs": community/motifs.md
    - "Nestedness": community/nestedness.md
  - "Species-level measures":
    - "Specificity": species/specificity.md
    - "Centrality": species/centrality.md
    - "Food-web specific": species/foodweb.md
  - "Hypothesis testing":
    - "Probabilistic null models": nhst/nullmodels.md
    - "Network permutations": nhst/swaps.md
    - "Null Hypothesis Significance Testing": nhst/nhst.md
